{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "go-grpc-http-rest-service.serviceAccountName" . }}
  labels:
{{ include "go-grpc-http-rest-service.labels" . | nindent 4 }}
{{- end -}}
